### ISSUE TITLE
t460s i5-6300u can use it ?

### ISSUE THREAD

**Issue by qinkangdeid** [naikoob/t460s-hackintosh#1]
My T460s
i5-6300U
Intel HD520 graphics
touch 1920x1080 display
Replaced Wifi/BT with (DW1850)
Samsung SM951 SSD

**Comment by naikoob** [comment]
I can't tell for sure as mine config is slightly different. However, your may want to have a look here -> https://www.insanelymac.com/forum/topic/315451-guide-lenovo-t460-macos-with-clover/
